### ISSUE TITLE
请问管理员账号如何设置?

### ISSUE THREAD

**Issue by duxuanhui** [ZhuFaner/shadowsocks-manage-system#10]

**Comment by zzjzz9266a** [comment]
把系统跑起来你就知道了

**Comment by duxuanhui** [comment]
现在已经跑起来了.....😳,只有登录/注册...

**Comment by duxuanhui** [comment]
@zzjzz9266a 大神,没有默认的管理员密码吗?

**Comment by johnlui** [comment]
尝试一下注册？

**Comment by duxuanhui** [comment]
啊........ 原来是这样的....我以为是类似moess的那种.....😳...谢谢

**Comment by johnlui** [comment]
注册完之后记得关掉注册功能呦

**Comment by duxuanhui** [comment]
恩,好的,谢谢大神

**Comment by duxuanhui** [comment]
@johnlui 如何关闭注册功能啊......😔  我是直接去views里面直接注释掉app.blade.php的那句代码的....有什么问题吗? 大神

**Comment by duxuanhui** [comment]
不行,😂,直接打链接就出来了.....

**Comment by johnlui** [comment]
刚刚更新了，有了这个功能

From My iPhone

**Comment by duxuanhui** [comment]
@johnlui 好的,谢谢大神
