### ISSUE TITLE
关于 Swoole 的作用探讨

### ISSUE THREAD

**Issue by Basic2016** [ZhuFaner/shadowsocks-manage-system#12]
README 文档中有这么一句话：
> Swoole 进程独立运行，每隔 5 秒查询一次数据库，将所有的端口号-密码组合向 ssserver 添加一遍（确实很 dirty，但是没办法）

但根据 ss 的[文档](https://github.com/shadowsocks/shadowsocks/wiki/Manage-Multiple-Users)，我们只需在添加账号时发送个 UDP 数据 `add: {"server_port": 8001, "password":"7cd308cc059"}` 不就可以了吗？每 5s 就添加一次是否多此一举？

**Comment by johnlui** [comment]
因为 ssserver 没有查询现有账号的 api，我们不知道已经添加了哪些，就不知道应该添加哪些。。。

**Comment by johnlui** [comment]
噢，懂你的意思了，这么做是因为 ssserver 在添加账号之后，udp 连接无法释放（用于接收流量），导致 PHP 进程被阻塞。删除就没有这个问题，所以是 web 直接做的。

**Comment by Basic2016** [comment]
好的~谢谢~
