### ISSUE TITLE
配置错误问题

### ISSUE THREAD

**Issue by ydxred** [ZhuFaner/shadowsocks-manage-system#2]
{
    "server": "0.0.0.0",
    "port_password": {
        "6001": ""
    },
    "timeout": 300,
    "method": "aes-256-cfb"
}
    server这里填写代理服务器吗?
为什么我运行是这样啊
xss@xss:/var/www/shadowsocks-manage-system# ssserver --manager-address 0.0.00:6001 -c /var/www/shadowsocks-manage-system/shadowsocks.json -d restart
INFO: loading config from /var/www/shadowsocks-manage-system/shadowsocks.json
2017-04-14 18:49:20 INFO     loading libcrypto from libcrypto.so.1.0.2
2017-04-14 18:49:20 ERROR    not running
started
xss@xss:/var/www/shadowsocks-manage-system# 

填写代理ip还是包 报这样的错  大神可以建个群讨论学习吗?

**Comment by TroyRay** [comment]
shadowsocks.json仅仅是让手动添加端口的配置文件，你可以手动在里面添加需要翻墙的端口，也可以不运行这个配置文件，直接运行ssserver --manager-address 0.0.0.0:6001  -d start也是OK的，如果你想看到log，就直接运行ssserver --manager-address 0.0.0.0:6001，就可以看到端口的配置情况了。还有你上面的ip写错了哈，少了个点

**Comment by ydxred** [comment]
诶!为什么我服务器配置都好了也成功的启动,账号密码端口也添加了!为什么链接不上啊 都有用的什么链接工具啊  我是win7设置新的连接或网络....

**Comment by TroyRay** [comment]
命令行运行ssserver --manager-address 0.0.0.0:6001，看ssserver是否正确启动，另起一个窗口执行php SwooleTask.php看是否有收到Receive OK。使用小飞机，也就是shadowsocks的windows客户端配置已经添加到ssserver的端口号
![image](https://cloud.githubusercontent.com/assets/8155310/25062524/30210bf2-2200-11e7-8277-940ec6c5663d.png)

**Comment by ydxred** [comment]
大师傅留个联系方式请教一下啊!我以前也是用这个行不通!最近一直在折腾科学上网!这个项目使用了laravel后台添加账号,密码端口的啊  Shadowsocks貌似我没看见这类选项呢

**Comment by TroyRay** [comment]
刚建了一个qq交流群:347339542，你可以加一下方便交流 @ydxred
